fixes, tweaks

diff --git a/bin/didactic/gh-repo-promotion-request b/bin/didactic/gh-repo-promotion-request
--- a/bin/didactic/gh-repo-promotion-request
+++ b/bin/didactic/gh-repo-promotion-request
@@ -1,12 +1,10 @@
 #!/bin/sh
-PROG=gh-repo-auth-request
-DESC="Submit a deployment authorization request"
+PROG=gh-repo-promotion-request
+DESC="Submit a deployment promotion request"
 USAGE1="${PROG}"
 
-DIDACTIC_GH_REPO="https://github.com/gwilliam-ucar-edu/didactic-mgr.git"
-
 HELP_DESC="
-This script implements the \"deployment authorization request\" component
+This script implements the \"deployment promotion request\" component
 of the didactic framework. It submits a GitHub \"pull request\" that
 requests the addition of an image metadata file to the appropriate
 didactic-mgr project/environment branch.
@@ -19,29 +17,33 @@ CIRCLE_PROJECT_REPONAME
     The git project reponame.
 
 DEPLOY_ENV
-    The target deployment environment to authorize.
+    The target deployment environment to promote to.
 
 IMAGE_METADATA
-    The path to a local copy of the current image metadata file.
+    The path to a local file containing image metadata.
+
+IMAGE_NAME
+    The docker image name without registry, repository, or tag components.
 
 IMAGE_TAG
-    The image tag to authorize.
+    The image tag to promote.
 "
 SCRIPTDIR=`cd \`dirname $0\`; pwd`
 . ${SCRIPTDIR}/didactic.rc || exit 1
 
 check-envvars --prog="${PROG}" DIDACTIC_INIT
 if [ $? != 0 ] ; then
-    echo "${PROG}: didactic has not been initialized. Run \"didactic init\"" >&2
+    echo "${PROG}: didactic has not been initialized. Run \"didactic-init\"" >&2
     exit 1
 fi
 check-envvars --prog="$PROG" CIRCLE_PROJECT_USERNAME CIRCLE_PROJECT_REPONAME \
                              DEPLOY_ENV IMAGE_METADATA IMAGE_TAG
-
 if [ ! -s "${IMAGE_METADATA}" ] ; then
-    echo "${PROG}: No image available for ${CIRCLE_TAG}" >&2
+    echo "${PROG}: No image available for ${RELEASE_TAG}" >&2
     exit 1
 fi
+
+. gh-repo.rc
 
 branch="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${DEPLOY_ENV}"
 tstamp=`echo "${IMAGE_TAG}" | sed -e 's/[^-]*-\([0-9]*T[0-9]*Z\).*/\1/'`
@@ -55,24 +57,25 @@ mkdir -p "${parent}" || exit 1
 
 git clone --branch ${branch} --depth 1 ${DIDACTIC_GH_REPO} "${CLONE_DIR}"
 if [ $? != 0 ] ; then
-    echo "${PROG}: unable to clone ${REPO} branch=${branch}" >&2
+    echo "${PROG}: unable to clone ${GH_REPO} branch=${branch}" >&2
     exit 1
 fi
 
 cd ${CLONE_DIR}
+ASSET="${IMAGE_NAME}--${IMAGE_TAG}"
 
 vecho "Running git checkout -b ${TEMP_BRANCH}"
 git checkout -b ${TEMP_BRANCH}
 
 revision=`git rev-parse HEAD`
 url=`git config --get remote.origin.url`
-desc="New unapproved image (${IMAGE_TAG}) for ${branch}"
+desc="New unapproved image (${ASSET}) for ${branch}"
 
-vecho "Copying ${IMAGE_METADATA} to ${IMAGE_TAG}"
-cp "${IMAGE_METADATA}" "${IMAGE_TAG}"
+vecho "Copying ${IMAGE_METADATA} to ${ASSET}"
+cp "${IMAGE_METADATA}" "${ASSET}"
 
-vecho "Running git add ${IMAGE_TAG}..."
-git add "${IMAGE_TAG}"
+vecho "Running git add "${ASSET}"..."
+git add "${ASSET}"
 
 vecho "Running git commit..."
 git commit -m "${desc}"
@@ -88,8 +91,8 @@ body="{
   \"maintainer_can_modify\": false
 }"
 vecho "Pull request POST body: ${body}"
-vecho "Running github-post /repos/${REPO}/pulls..."
-resp=`echo "${body}" | github-post /repos/${REPO}/pulls`
+vecho "Running github-post /repos/${GH_REPO}/pulls..."
+resp=`echo "${body}" | github-post /repos/${GH_REPO}/pulls`
 vecho "Response=${resp}"
 
 echo "Request queued with GitHub"
